/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CandidateIndexRouteImport } from './routes/candidate/index'
import { Route as CandidateSessionIdRouteImport } from './routes/candidate/$sessionId'
import { Route as DashboardProblemsIndexRouteImport } from './routes/dashboard/problems.index'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/dashboard/sessions.$sessionId'
import { Route as CandidateSessionIdCompleteRouteImport } from './routes/candidate/$sessionId_.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateSessionIdRoute = CandidateSessionIdRouteImport.update({
  id: '/candidate/$sessionId',
  path: '/candidate/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProblemsIndexRoute = DashboardProblemsIndexRouteImport.update({
  id: '/dashboard/problems/',
  path: '/dashboard/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSessionsSessionIdRoute =
  DashboardSessionsSessionIdRouteImport.update({
    id: '/dashboard/sessions/$sessionId',
    path: '/dashboard/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CandidateSessionIdCompleteRoute =
  CandidateSessionIdCompleteRouteImport.update({
    id: '/candidate/$sessionId_/complete',
    path: '/candidate/$sessionId/complete',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate/$sessionId': typeof CandidateSessionIdRoute
  '/candidate/': typeof CandidateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/candidate/$sessionId/complete': typeof CandidateSessionIdCompleteRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/problems/': typeof DashboardProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate/$sessionId': typeof CandidateSessionIdRoute
  '/candidate': typeof CandidateIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/candidate/$sessionId/complete': typeof CandidateSessionIdCompleteRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/problems': typeof DashboardProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate/$sessionId': typeof CandidateSessionIdRoute
  '/candidate/': typeof CandidateIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/candidate/$sessionId_/complete': typeof CandidateSessionIdCompleteRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/dashboard/problems/': typeof DashboardProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate/$sessionId'
    | '/candidate/'
    | '/dashboard/'
    | '/candidate/$sessionId/complete'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate/$sessionId'
    | '/candidate'
    | '/dashboard'
    | '/candidate/$sessionId/complete'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/problems'
  id:
    | '__root__'
    | '/'
    | '/candidate/$sessionId'
    | '/candidate/'
    | '/dashboard/'
    | '/candidate/$sessionId_/complete'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateSessionIdRoute: typeof CandidateSessionIdRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  CandidateSessionIdCompleteRoute: typeof CandidateSessionIdCompleteRoute
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
  DashboardProblemsIndexRoute: typeof DashboardProblemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/$sessionId': {
      id: '/candidate/$sessionId'
      path: '/candidate/$sessionId'
      fullPath: '/candidate/$sessionId'
      preLoaderRoute: typeof CandidateSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/problems/': {
      id: '/dashboard/problems/'
      path: '/dashboard/problems'
      fullPath: '/dashboard/problems/'
      preLoaderRoute: typeof DashboardProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sessions/$sessionId': {
      id: '/dashboard/sessions/$sessionId'
      path: '/dashboard/sessions/$sessionId'
      fullPath: '/dashboard/sessions/$sessionId'
      preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/$sessionId_/complete': {
      id: '/candidate/$sessionId_/complete'
      path: '/candidate/$sessionId/complete'
      fullPath: '/candidate/$sessionId/complete'
      preLoaderRoute: typeof CandidateSessionIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateSessionIdRoute: CandidateSessionIdRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  CandidateSessionIdCompleteRoute: CandidateSessionIdCompleteRoute,
  DashboardSessionsSessionIdRoute: DashboardSessionsSessionIdRoute,
  DashboardProblemsIndexRoute: DashboardProblemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
